language: python
dist: bionic
python:
  - "3.7"
  - "3.8"
env:
  global:
    - PIPENV_VERBOSITY=-1
    - PYTHON_PIP_VERSION=21.0.1
    - PYTHON_PIPENV_VERSION=2020.11.15
  matrix:
    - TASKWARRIOR_VERSION=2.5.1
    - TASKWARRIOR_VERSION=2.5.3
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gnutls-dev pandoc uuid-dev
  - wget http://taskwarrior.org/download/task-$TASKWARRIOR_VERSION.tar.gz
  - gunzip task-$TASKWARRIOR_VERSION.tar.gz
  - tar xf task-$TASKWARRIOR_VERSION.tar
  - cd task-$TASKWARRIOR_VERSION
  - cmake .
  - make
  - sudo make install
  - task --version
  - pip install pip==$PYTHON_PIP_VERSION
  - pip install pipenv==$PYTHON_PIPENV_VERSION
  - cd $TRAVIS_BUILD_DIR
install:
  - pipenv install --deploy --dev
script: pytest --cov=bugwarrior --cov-branch tests
after_success: codecov
notifications:
  email:
    on_success: change
    on_failure: always
