dist: xenial
sudo: required
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
env:
  global:
    - PIPENV_VERBOSITY=-1
    - PYTHON_PIP_VERSION=18.1
    - PYTHON_PIPENV_VERSION=2018.11.26
  matrix:
    - TASKWARRIOR_VERSION=2.5.0
    - TASKWARRIOR_VERSION=2.5.1
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y uuid-dev pandoc
  - wget http://taskwarrior.org/download/task-$TASKWARRIOR_VERSION.tar.gz
  - gunzip task-$TASKWARRIOR_VERSION.tar.gz
  - tar xf task-$TASKWARRIOR_VERSION.tar
  - cd task-$TASKWARRIOR_VERSION
  - cmake .
  - make
  - sudo make install
  - task --version
  - pip install pip==$PYTHON_PIP_VERSION
  - pip install pipenv==$PYTHON_PIPENV_VERSION
  - cd $TRAVIS_BUILD_DIR
install:
  - pipenv install --deploy --dev
script: nosetests -w tests --with-coverage --cover-branches --cover-package=bugwarrior -v
after_success: codecov
notifications:
  email:
    on_success: change
    on_failure: always
